name: Build

on:
  push:
    branches:
      - master
      - develop
      - "feature/**"
      - "release/**"
      - "hotfix/**"
    tags:
      - "*"
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-24.04, macos-13]

    env:
      AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
      AZURE_SOURCE: ${{ secrets.AZURE_SOURCE }}
      AZURE_USER: ${{ secrets.AZURE_USER }}
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
      GPR_PASSWORD: ${{ secrets.GPR_PASSWORD }}
      GPR_SOURCE: ${{ secrets.GPR_SOURCE }}
      GPR_USER: ${{ secrets.GPR_USER }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      NUGET_SOURCE: "https://api.nuget.org/v3/index.json"
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      WYAM_ACCESS_TOKEN: ${{ secrets.WYAM_ACCESS_TOKEN }}
      WYAM_DEPLOY_BRANCH: "gh-pages"
      WYAM_DEPLOY_REMOTE: ${{ github.event.repository.html_url }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow

      - name: Cache Tools
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake', '.config/dotnet-tools.json') }}

      # install libgit2-dev on ubuntu, so libgit2sharp works
      - name: Install libgit-dev
        if: runner.os == 'Linux'
        run: sudo apt-get install -y libgit2-dev

      - name: Setup required dotnet versions
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: |
            2.1.818
            3.1.x
            5.0.x
            6.0.x
            7.0.x
            8.0.x
            9.0.x
      # Ubuntu 24.04 does not have Mono installed, which is Required for Cake.Recipe
      - name: Install Mono
        if: ${{ matrix.os == 'ubuntu-24.04' }}
        run: sudo apt-get install mono-complete
      - name: Build project
        uses: cake-build/cake-action@d218f1133bb74a1df0b08c89cfd8fc100c09e1a0 # v3.0.1
        with:
          cake-bootstrap: explicit
          script-path: recipe.cake
          target: CI
          verbosity: Normal
          cake-version: tool-manifest

      - name: Upload Issues-Report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          if-no-files-found: warn
          name: ${{ matrix.os }} Issues
          path: BuildArtifacts/report.html

      - name: Upload Packages
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          if-no-files-found: warn
          name: package
          path: BuildArtifacts/Packages/**/*